# Generated by Django 4.1.2 on 2022-11-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.CharField(max_length=122)),
                ('user', models.CharField(max_length=122)),
                ('question', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
