# Generated by Django 4.1.2 on 2022-11-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contact_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='id',
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
