# Generated by Django 4.1.2 on 2022-11-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_questions_id_alter_questions_q_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.IntegerField(max_length=12)),
                ('user', models.CharField(max_length=122)),
                ('answere', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
