# Generated by Django 4.1.2 on 2022-11-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_answere_q_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answere',
            name='q_number',
            field=models.CharField(max_length=122),
        ),
    ]
